### PR TITLE
Add small bubblewrap like program as a build step

### PR DESCRIPTION
**Pull request by MaxHearnden**
This allow the user to perform a rootless build without bubblewrap on machines with user namespaces enabled

### CODE REVIEW

**Comment by fosslinux** [comment]
I understand the idea/implementation in principle. Would you mind outlining any particular, specific usecases for this?

**Comment by MaxHearnden** [comment]
It's to reduce the binary seed required for an unprivileged build to just hex0+kaem-optional and can be used with the following commands
```
cp sysa/stage0-posix/src/* .
cp sysa/after_wrap.kaem after.kaem

# This stage could be integrated into after_wrap.kaem
echo "CHROOT=True
CHROOT_WRAP=True" >> sysa/bootstrap.cfg

./bootstrap-seeds/POSIX/x86/kaem-optional-seed
```

**Comment by oriansj** [comment]
I like it but 2 minor details:
1) the syscalls should added to M2libc such that the code becomes more standard C.
2) the wrap.c program belongs in mescc-tools-extra which live-bootstrap does already use and will allow other bootstrapping projects to leverage your work.

great work

**Comment by fosslinux** [comment]
If this could be

1. rebased on master
2. updated to reflect that wrap.c is in mescc-tools-extra

I think I'm happy to include this in principle.

**Comment by Googulator** [comment]
#436 will bring in wrap.c into live-bootstrap, although currently unused

**Comment by MaxHearnden** [comment]
Replaced by https://github.com/fosslinux/live-bootstrap/pull/479

**Pull request closed without merging**
