### PR TITLE
Rebuild musl libc after building tcc-musl

### PR DESCRIPTION
**Pull request by pder**
This fixes an issue with printf not printing doubles or floats
correctly, and probably other subtle issues.

### CODE REVIEW

**Review by stikonas — APPROVED** [review]
Should we add a new "Part" for musl recompilation?

**Comment by fosslinux** [comment]
Yes, I think we should.

**Comment by stikonas** [comment]
Also as discussed on IRC, it probably makes sense to rebuild tcc again, so that tcc itself has working floats (in case it uses them).

**Comment by fosslinux** [comment]
Please rebase. It would be nice to also rebuild tcc as @stikonas mentioned about. I can do checksums if you want cause this is rather painful.

**Comment by fosslinux** [comment]
Merged with a couple of changes.

**Pull request closed without merging**
