### PR TITLE
Update to mes-0.26.1.

### PR DESCRIPTION
**Pull request by stikonas**
Somehow this seems to break kernel bootstrap... Not sure why.

~Also tcc riscv64 checksum still needs updating.~

### CODE REVIEW

**Comment by stikonas** [comment]
Looks like Fiwix hasn't started booting yet when crash happens:
```
Fiwix ext2 initrd created successfully.
 +> if match xFalse xTrue 
kexec-fiwix: starting kernel /boot/fiwix...

kexec-fiwix: Fiwix kernel file length: 375788
kexec-fiwix: Reading kernel...
ELF virtual entry point       : 0x80100030
ELF program header offset     : 0x34
ELF number of program  headers: 2
ELF size of program  headers  : 32
kexec-fiwix: Placing kernel in memory...
ELF physical entry point      : 0x100030
header 0:
    p_offset: 0x00001000
    p_paddr : 0x00100000
    p_filesz: 0x0004b5a4
    p_memsz : 0x0004b5a4
header 1:
    p_offset: 0x0004c5a4
    p_paddr : 0x0014c5a4
    p_filesz: 0x0000f4c4
    p_memsz : 0x00037df0
Preparing multiboot info for kernel...
Found image at filenum 9095
initrd_src: 0x68221188
initrd_len: 0x54500000
kexec-fiwix: Memory map file length: 192
kexec-fiwix: Reading memory map file...
Preparing trampoline...
kexec-fiwix: jumping to trampoline..
```

**Comment by stikonas** [comment]
Hmm, downgrading back just tcc to the old version works. So one of those patches...

**Comment by stikonas** [comment]
For now I've removed tinycc upgrade as it was causing issues with Fiwix. It should be easier to debug if we decouple mes and tinycc upgrade.

This means that riscv64 bootstrap regressed a bit (as new mes removed some special casing for tcc assembly support but we are not using that newer tcc yet), hence I changed target branch to `master`.

**Comment by stikonas** [comment]
CI is expected to eventually fail due to openssl download URL (see https://github.com/fosslinux/live-bootstrap/pull/472)

**Review by Googulator — COMMENTED** [review]
Looking good - please update parts.rst and rebase so we can get a clean CI.

**Review by fosslinux — APPROVED** [review]

**Pull request merged**
