### PR TITLE
Avoid deleting sources that will be needed in future builds and fix updating checksums with `--update-checksums`

### PR DESCRIPTION
**Pull request by eduardosm**

### CODE REVIEW

**Comment by Googulator** [comment]
FYI, I've also posted a PR with very similar goals (https://github.com/fosslinux/live-bootstrap/pull/361) without noticing this one; in that, I've gotten quite a bit more working. However, commits https://github.com/fosslinux/live-bootstrap/pull/360/commits/22957b89a8a491dc636e795beae10c6adaf5cafc and https://github.com/fosslinux/live-bootstrap/pull/360/commits/ab86370e99858b8d762bbb6efb9f178a10981627 will still be relevant after my work, so please keep this PR around.

**Comment by fosslinux** [comment]
This PR looks fairly good, thanks for the cleanups. Could you rebase this on master, then I'll take a second look at it?

**Comment by eduardosm** [comment]
Done. As expected, only the two mentioned commits remain.

**Comment by Googulator** [comment]
The remaining CI failure is the one fixed by https://github.com/fosslinux/live-bootstrap/commit/9179f4bd013fbd323d11d861a0c15f37a94f8c5b, and should go away when this is merged.

**Comment by eduardosm** [comment]
Rebased to pick that commit

**Review by fosslinux — APPROVED** [review]
Thank you!

**Pull request merged**
