### PR TITLE
gcc 13.1.0: don't enable default ssp or pie

### PR DESCRIPTION
**Pull request by pder**
The combination of --enable-default-ssp and the modifications to musl were causing gcc to produce binaries that segfault on startup.  Also turn off --enable-default-pie.  These features can be enabled later when a future toolchain is built.

### CODE REVIEW

**Comment by fosslinux** [comment]
Was it confirmed that PIE was a cause of segfaults?

**Comment by pder** [comment]
It has not been confirmed yet that pie was the reason for the segfaults doras experienced.

**Review by stikonas — APPROVED** [review]

**Comment by fosslinux** [comment]
I'm not convinced this is the end of the story, but I need to do a bit more digging.

**Comment by doraskayo** [comment]
@fosslinux, @pder, @stikonas: I'm happy to share that this PR solved the segmentation faults we've seen with GCC 13.1.0. See: https://gitlab.com/freedesktop-sdk/freedesktop-sdk-binary-seed/-/pipelines/951421539

I've made two tests, one only with the removal of `--enable-default-pie`  and another with the removal of both `--enable-default-pie`  and `--enable-default-ssp`. While the first reduced the number of segmentation faults seen, the second was required to solve the issue entirely.

**Pull request merged**
