### PR TITLE
Fix Python 2.5.6 for parallel pgen invocation

### PR DESCRIPTION
**Pull request by nanonyme**
Backported from https://github.com/python/cpython/commit/9828b56347f6171a532dce28c9dc5ab9bd2c8139.patch
Fixes https://github.com/fosslinux/live-bootstrap/issues/321

### CODE REVIEW

**Comment by nanonyme** [comment]
@fosslinux looks like build is failing as part of pkg-config removal. I'm running a pipelien on our side at https://gitlab.com/freedesktop-sdk/freedesktop-sdk-binary-seed/-/jobs/5467602634

**Comment by nanonyme** [comment]
We are mirroring our sources so the removal doesn't really impact us. We are using method for obtaining sources that is similar to bwrap method.

**Comment by nanonyme** [comment]
Unfortunately it looks like this patch changes hashes. I will need to find out if they are changed in a reproducible way.

**Comment by fosslinux** [comment]
Yes, the pkg-config thing is expected to fail builds at the moment.

Many things can change hashes, I'm not particularly concerned that hashes are changed - just that the new hash is always the same :)

**Comment by nanonyme** [comment]
Does the pkg-config situation effectively mean nothing can be merged for the time being?

**Comment by fosslinux** [comment]
The CI should still pass, because it's using download-distfiles.sh (external distfiles)...

Things can still be merged.

**Comment by nanonyme** [comment]
This CI ironically would most likely be considerably faster with parallel build on.

**Comment by nanonyme** [comment]
@fosslinux it seems this new hash reproduced multiple times so I'm hopeful that it persists. I suspect there is one extra file (the timestamp file) as a result of the patch.

**Comment by fosslinux** [comment]
The CI already runs with `--cores 2`, which is what the runners have available.. https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Review by fosslinux — APPROVED** [review]
LGTM

**Pull request merged**
