### PR TITLE
Boot Fiwix and Linux without serial console on bare metal

### PR DESCRIPTION
**Pull request by pder**

### CODE REVIEW

**Review by stikonas — APPROVED** [review]
That seems to only change Fiwix kernel options. Or does it also propagate to Linux?

**Review by fosslinux — COMMENTED** [review]
Similar change to go_sysb would be good (so that console=ttyS0 is not used for sysc).

**Comment by pder** [comment]
> That seems to only change Fiwix kernel options. Or does it also propagate to Linux?

kexec_cmdline are the parameters passed to Linux.

kexec_cmdline=\"init=/init console=ttyS0\"

**Comment by pder** [comment]
> Similar change to go_sysb would be good (so that console=ttyS0 is not used for sysc).

OK, so would this be for the case we are using the bare-metal option and providing a kernel?

**Comment by stikonas** [comment]
No, just the different transition. You updated builder-hex0 to fiwix but there is Fiwix to Linux here: https://github.com/fosslinux/live-bootstrap/blob/master/sysa/run2.sh#L38

**Comment by pder** [comment]
> No, just the different transition. You updated builder-hex0 to fiwix but there is Fiwix to Linux here: https://github.com/fosslinux/live-bootstrap/blob/master/sysa/run2.sh#L38

The Fiwix to Linux transition happens here: 
https://github.com/fosslinux/live-bootstrap/blob/master/sysa/run2.sh#L29

rickmasters created kexec-linux that is what sets up Linux for kexecing from Fiwix

**Comment by stikonas** [comment]
> > No, just the different transition. You updated builder-hex0 to fiwix but there is Fiwix to Linux here: https://github.com/fosslinux/live-bootstrap/blob/master/sysa/run2.sh#L38
> 
> The Fiwix to Linux transition happens here: https://github.com/fosslinux/live-bootstrap/blob/master/sysa/run2.sh#L29
> 
> rickmasters created kexec-linux that is what sets up Linux for kexecing from Fiwix

Oh indeed, we have a different path for bootstrapping. That other kexec only happens if we start with another linux kernel.

Though I'm still trying to understand where do we pass linux command line to kexec-linux..

**Comment by fosslinux** [comment]
Huh, but where *is* the cmdline for sysc in kernel bootstrap mode? Does it exist?

**Comment by stikonas** [comment]
> Huh, but where _is_ the cmdline for sysc in kernel bootstrap mode? Does it exist?

Yes, see irc logs on #bootsrappable. On Fiwix future kexec cmdline has to be set in advance inside Fiwix cmdline (kexec_cmdline parameter)

**Comment by stikonas** [comment]
https://github.com/mikaku/Fiwix/issues/29 documents this a bit.

**Review by fosslinux — CHANGES_REQUESTED** [review]
Consensus is could you please add the change to `go_sysb` in `sysa/run2.sh` as well? For when kernel bootstrap is not used.

**Comment by fosslinux** [comment]
You would use GRUB or something similar and then `linux path/to/kernel` and `initrd path/to/initramfs`.

**Comment by stikonas** [comment]
Hmm, it's probably fine to just test this in qemu... We never really tested GRUB before anyway. Though if you can, that would be an interesting test.

**Comment by fosslinux** [comment]
I have once before, but it's been a fair while since I've tested it..

**Review by stikonas — APPROVED** [review]

**Pull request merged**
