### PR TITLE
Build and install cp from coreutils to replace our minimal cp

### PR DESCRIPTION
**Pull request by pder**
Also update tcc-musl.sh to take advantage that cp can now copy
recursively

### CODE REVIEW

**Review by stikonas — APPROVED** [review]

**Comment by fosslinux** [comment]
Please add a checksum for ls.

**Comment by stikonas** [comment]
> Please add a checksum for ls.

It's actually checksum for `cp` not `ls`.

**Comment by stikonas** [comment]
Updated pass1 checksum for `cp` is

```
5a869b028ce076d0a2ee06721956f38128a7d82d68be61e223a3051fbbb59e90  cp
```

**Comment by stikonas** [comment]
Rebased, fixed and integrated into https://github.com/fosslinux/live-bootstrap/pull/44.

**Pull request closed without merging**
