### PR TITLE
Update URL for openssl-3.0.13.tar.gz

### PR DESCRIPTION
**Pull request by pyy**

### CODE REVIEW

**Comment by Googulator** [comment]
OpenSSL is what enables access to HTTPS URLs, so we can't pull OpenSSL via HTTPS.

**Comment by stikonas** [comment]
Also target branch is incorrect, it should go to 1.0 branch.

**Comment by stikonas** [comment]
> > OpenSSL is what enables access to HTTPS URLs, so we can't pull OpenSSL via HTTPS.
> 
> But the old link is invalid. Should we use third-party repos, like some linux repos to get openssl-3.0.13.tar.gz?

I think third-party mirror should be fine. See if there is anything with 3.0.13.

**Comment by Googulator** [comment]
See also: https://github.com/openssl/openssl/issues/24706

**Comment by stikonas** [comment]
On #bootstrappable BearSSL was mentioned, longer term it might be worth looking into including that into pre-network part of bootstrap. Though perhaps for short term we could switch to HTTP mirror.

**Pull request closed without merging**
