### PR TITLE
Rename /usr/lib/musl to /usr/lib/i386-unknown-linux-musl

### PR DESCRIPTION
**Pull request by doraskayo**
## Overview
The triplet form is a more explicit and standard name for the system libraries directory. Some projects even assume its presence these days.

A new `LIBDIR` variable is introduced to ease this transision and avoid duplication in many build scripts.

See commit messages for more information.

### Before
``` bash
/ # ls -l /usr/lib 
total 72
-rw-r--r--  1 0 0   217 Jan  1  1970 charset.alias
lrwxrwxrwx  1 0 0    12 Jan  1  1970 ld-musl-i386.so.1 -> musl/libc.so
drwxr-xr-x  2 0 0  4096 Jan  1  1970 ldscripts
drwxr-xr-x 14 0 0  4096 Jan  1  1970 musl
drwxr-xr-x  4 0 0  4096 Jan  1  1970 perl5
drwxr-xr-x 12 0 0  4096 Jan 28 21:21 python2.0
drwxr-xr-x 19 0 0 12288 Jan 28 21:25 python2.3
drwxr-xr-x 21 0 0 12288 Jan 28 21:27 python2.5
drwxr-xr-x 26 0 0 12288 Jan 28 21:30 python3.1
drwxr-xr-x 38 0 0  4096 Jan  1  1970 python3.11
drwxr-xr-x 33 0 0  4096 Jan  1  1970 python3.3
drwxr-xr-x 35 0 0  4096 Jan  1  1970 python3.4
drwxr-xr-x 34 0 0  4096 Jan  1  1970 python3.8
```

### After
``` bash
/ # ls -l /usr/lib
total 72
-rw-r--r--  1 0 0   217 Jan  1  1970 charset.alias
drwxr-xr-x 14 0 0  4096 Jan  1  1970 i386-unknown-linux-musl
lrwxrwxrwx  1 0 0    31 Jan  1  1970 ld-musl-i386.so.1 -> i386-unknown-linux-musl/libc.so
drwxr-xr-x  2 0 0  4096 Jan  1  1970 ldscripts
drwxr-xr-x  4 0 0  4096 Jan  1  1970 perl5
drwxr-xr-x 12 0 0  4096 Jan 28 21:21 python2.0
drwxr-xr-x 19 0 0 12288 Jan 28 21:25 python2.3
drwxr-xr-x 21 0 0 12288 Jan 28 21:27 python2.5
drwxr-xr-x 26 0 0 12288 Jan 28 21:30 python3.1
drwxr-xr-x 38 0 0  4096 Jan  1  1970 python3.11
drwxr-xr-x 33 0 0  4096 Jan  1  1970 python3.3
drwxr-xr-x 35 0 0  4096 Jan  1  1970 python3.4
drwxr-xr-x 34 0 0  4096 Jan  1  1970 python3.8
```

## Testing
This was tested in the `bwrap` and `qemu` bootstrap modes.

cc: @fosslinux, @stikonas

### CODE REVIEW

**Review by stikonas — CHANGES_REQUESTED** [review]
on #bootstrappable @fosslinux suggested that we switch to `i386-unknown-linux-musl` rather than `i386-linux-musl`.

**Comment by doraskayo** [comment]
MR with CI for `freedesktop-sdk-binary-seed` here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk-binary-seed/-/merge_requests/27

**Comment by doraskayo** [comment]
I went over the changes in the packages and they seem to make sense. The only change is library directory path being modified in every file where it's embedded.

**Review by fosslinux — APPROVED** [review]
I will just run a build of this and then merge.

**Pull request merged**
